# Generated by Django 5.2.8 on 2025-12-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_delete_emplayee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='designamtion',
            new_name='designation',
        ),
    ]
