# Generated by Django 5.2.8 on 2025-12-10 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_rename_designamtion_employee_designation'),
    ]

    operations = [
    ]
